name: Run Newman Tests

on:
    push:
        branches: ["master"]

jobs:
    newman-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install newman and html reporter
              run: npm install -g newman newman-reporter-htmlextra

            - name: Run API Tests
              run: |
                  newman run postman/DummyApi.postman_collection.json \
                    --reporters cli,htmlextra \
                    --reporter-htmlextra-export newman-report.html

            - name: Check generated files
              run: ls -al

            - name: Upload HTML Report
              uses: actions/upload-artifact@v4
              with:
                  name: newman-html-report
                  path: ./newman-report.html
